#!/usr/bin/env python3
"""
gen_reference.py
================
Generates:
  1. NODE_IDX values (seed=42, Layer 0) — used to verify RTL constants
  2. A small FP32 software reference for one spatial location:
       e_in (64-d) → T=20 reservoir steps → fb (64-d)
     These are written as hex literals for use in the SV testbenches.
  3. precision.md quantization error analysis (Xyce analog vs FP32 SW model)

Usage:
    python3 gen_reference.py

Outputs:
    tb_reference_values.svh   — `include file for testbenches
    node_idx_check.txt        — human-readable node index list

ECE 510 Spring 2026 — Milestone 2
"""
import numpy as np
import struct
import os

# ============================================================
# Reservoir hyperparameters — must match SpatialTiledReservoir
# ============================================================
SEED     = 42
N_IN     = 64    # input channels Layer 0
N_OUT    = 64    # output channels Layer 0
N_RES    = 128   # reservoir nodes = 2 * N_OUT
T        = 20    # recurrent steps
SR       = 0.95  # spectral radius
LAT      = 0.1   # lateral strength (used in full kernel, not this scalar ref)

rng = np.random.RandomState(SEED)

# Weights — identical construction to SpatialTiledReservoir.__init__
W_in_np  = rng.randn(N_RES, N_IN).astype(np.float32) * 0.1
W_raw    = rng.randn(N_RES, N_RES).astype(np.float32)
eigs     = np.linalg.eigvals(W_raw)
W_res_np = (W_raw * (SR / np.max(np.abs(eigs)))).astype(np.float32)

W_lat_np = np.zeros((N_RES, N_RES), dtype=np.float32)
for k in range(N_RES):
    nb = rng.choice(N_RES, size=4, replace=False)
    W_lat_np[k, nb] = rng.randn(4).astype(np.float32) * 0.1

flat_idx      = rng.choice(N_RES * T, size=N_OUT, replace=False)
node_idx_np   = (flat_idx % N_RES).astype(np.int64)
time_idx_np   = (flat_idx // N_RES).astype(np.int64)

# ============================================================
# Generate reference output for one spatial location
# Use a reproducible non-trivial input vector
# ============================================================
rng2 = np.random.RandomState(1234)
e_raw = rng2.randn(N_IN).astype(np.float32)

# Normalise (matches get_feedback_map)
norm  = np.linalg.norm(e_raw) + 1e-8
e_in  = (e_raw / norm).astype(np.float32)

# Forward pass: T steps
s = np.tanh(e_in @ W_in_np.T)        # shape (N_RES,), step 0
for _ in range(1, T):
    # lateral term omitted here (single-location scalar reference)
    # matches the analog crossbar which sees no spatial neighbours for 1-loc test
    s = np.tanh(s @ W_res_np.T)

fb_ref = s[node_idx_np].astype(np.float32)    # shape (N_OUT,)

# ============================================================
# Encode as packed hex for SystemVerilog $value$plusargs / parameters
# ============================================================
def fp32_to_hex(arr):
    """Return list of 8-digit hex strings for each FP32 element."""
    return [f"{struct.unpack('>I', struct.pack('>f', float(v)))[0]:08X}"
            for v in arr]

e_hex  = fp32_to_hex(e_in)
fb_hex = fp32_to_hex(fb_ref)

# ============================================================
# Write SystemVerilog include file
# ============================================================
svh_lines = [
    "// tb_reference_values.svh",
    "// Auto-generated by gen_reference.py — DO NOT EDIT",
    "// Reference FP32 software model for one spatial location, Layer 0",
    "// ECE 510 Spring 2026 — Milestone 2",
    "",
    f"// NODE_IDX[0..{N_OUT-1}] — readout index map",
    "// (copy to compute_core.sv localparam if regenerating)",
]
idx_chunks = [str(node_idx_np[i]) for i in range(N_OUT)]
svh_lines.append("// " + ", ".join(idx_chunks[:16]))
svh_lines.append("// " + ", ".join(idx_chunks[16:32]))
svh_lines.append("// " + ", ".join(idx_chunks[32:48]))
svh_lines.append("// " + ", ".join(idx_chunks[48:]))
svh_lines.append("")

# e_in packed hex (N_IN * 32 bits = 256 bytes = 2048 bits)
e_packed = "".join(reversed(e_hex))   # little-endian word packing
svh_lines.append(f"// e_in packed ({N_IN}×FP32, little-endian words)")
svh_lines.append(f"`define E_IN_PACKED {N_IN*32}'h{e_packed}")
svh_lines.append("")

# fb_ref packed hex
fb_packed = "".join(reversed(fb_hex))
svh_lines.append(f"// fb_ref packed ({N_OUT}×FP32, little-endian words)")
svh_lines.append(f"`define FB_REF_PACKED {N_OUT*32}'h{fb_packed}")
svh_lines.append("")

# Tolerance: allow ±1 LSB of FP32 mantissa per word (digital model)
# Full error analysis in precision.md
svh_lines.append("// Absolute tolerance per word: 2^-23 (1 ULP FP32)")
svh_lines.append("`define ABS_TOL_HEX 32'h33800000  // 5.96e-8")
svh_lines.append("")

with open("tb_reference_values.svh", "w") as f:
    f.write("\n".join(svh_lines) + "\n")

print("Wrote tb_reference_values.svh")

# ============================================================
# Human-readable node index file
# ============================================================
with open("node_idx_check.txt", "w") as f:
    f.write("NODE_IDX for Layer 0 (seed=42, N=128, T=20, N_OUT=64)\n")
    f.write("="*60 + "\n")
    for i, idx in enumerate(node_idx_np):
        f.write(f"  [{i:2d}] = {idx}\n")

print("Wrote node_idx_check.txt")

# ============================================================
# Quantization error analysis for precision.md
# Run 1000 random spatial locations, compare FP32 vs FP16 model
# ============================================================
N_SAMPLES = 1000
rng3 = np.random.RandomState(9999)
errors_fp16 = []
errors_bf16 = []

for _ in range(N_SAMPLES):
    e_r = rng3.randn(N_IN).astype(np.float32)
    e_r /= (np.linalg.norm(e_r) + 1e-8)

    # FP32 reference
    s32 = np.tanh(e_r @ W_in_np.T)
    for _ in range(1, T):
        s32 = np.tanh(s32 @ W_res_np.T)
    fb32 = s32[node_idx_np]

    # FP16 simulation (cast weights and activations)
    W_in_fp16  = W_in_np.astype(np.float16)
    W_res_fp16 = W_res_np.astype(np.float16)
    e_fp16 = e_r.astype(np.float16)
    s16 = np.tanh(e_fp16 @ W_in_fp16.T).astype(np.float16)
    for _ in range(1, T):
        s16 = np.tanh(s16 @ W_res_fp16.T).astype(np.float16)
    fb16 = s16[node_idx_np].astype(np.float32)

    errors_fp16.append(np.abs(fb32 - fb16))

errors_fp16 = np.concatenate(errors_fp16)

print(f"\nFP16 vs FP32 error over {N_SAMPLES} spatial locations:")
print(f"  Mean absolute error : {np.mean(errors_fp16):.6e}")
print(f"  Max absolute error  : {np.max(errors_fp16):.6e}")
print(f"  Std                 : {np.std(errors_fp16):.6e}")

# Write summary for precision.md generation
np.save("error_analysis.npy", {
    "mean_ae": float(np.mean(errors_fp16)),
    "max_ae":  float(np.max(errors_fp16)),
    "std_ae":  float(np.std(errors_fp16)),
    "n_samples": N_SAMPLES
})

print("\nSummary saved to error_analysis.npy")
print("\nFP32 reference output (first 8 words):")
for i, v in enumerate(fb_ref[:8]):
    print(f"  fb_ref[{i}] = {v:.8f}  (0x{struct.unpack('>I', struct.pack('>f', float(v)))[0]:08X})")
