# analog_arrival.tcl -- auto-generated by extract_rc_timing.py
# Source: ngspice crossbar_rc.sp -- 128x128 direct measurement
#
# TIMING
#   t_10     = 3.595 ps
#   t_90     = 18.013 ps
#   tau      = 6.562 ps  (0.006562 ns)
#   t_99     = 33.380 ps  (0.033380 ns)
#   BW       = 24.253 GHz
#   Margin   = 0.9934 ns @ 1 GHz  (PASS)
#
# POWER (128x128 full array)
#   Average  = 530.8416 uW
#
# ROUTING
#   Total    = 4.194 mm
#
# Input delay = t99 settling time
set_input_delay 0.033380 -clock clk [get_ports {adc_out}]
