// =============================================================================
// compute_core.sv
// RC-DFA Memcapacitive Reservoir Accelerator — Digital Compute Core
// ECE 510 Spring 2026 — Project Milestone 2
//
// PURPOSE
//   Digital wrapper for the 128x128 memcapacitive crossbar network that
//   accelerates SpatialTiledReservoir.get_feedback_map (76.3% of step time).
//   The analog crossbar is stubbed (analog_crossbar_stub). In co-simulation
//   the VPI shim overrides stub outputs with live Xyce node voltages.
//
// FUNCTIONAL DESCRIPTION
//   FSM sequences T sample cycles for one spatial location:
//     IDLE -> LOAD (latch e_in, pulse sample at t=0)
//          -> SAMPLE (pulse sample t=1..T-1, capture adc each pulse)
//          -> READOUT (gather NODE_IDX[j] from final adc capture)
//          -> DONE_ST (assert done, hold fb_out)
//
// PARAMETERS
//   N_RES   : reservoir nodes (128 = 2 x N_OUT)
//   N_IN    : input channels per spatial location (64, Layer 0)
//   N_OUT   : output feedback channels (64, Layer 0)
//   T_STEPS : recurrent sample steps (20, Layer 0)
//   DATA_W  : data word width in bits (32, FP32 boundary)
//
// PORTS
//   clk          : in  1            Clock (1 GHz in co-sim)
//   rst_n        : in  1            Active-low synchronous reset
//   start        : in  1            Pulse 1 cycle to begin computation
//   e_in         : in  N_IN*32      Packed FP32 normalised error vector
//   done         : out 1            High when fb_out is valid
//   fb_out       : out N_OUT*32     Packed FP32 feedback map output
//   sample_pulse : out 1            One-cycle pulse per reservoir timestep
//   dac_in       : out N_IN*32      Drives crossbar input DAC (latched e_in)
//   adc_out      : in  N_RES*32     Node voltages from crossbar (VPI-driven)
//
// CLOCK/RESET
//   Single clock domain. Synchronous active-low reset.
//
// SYNTHESIZABILITY
//   No delays, no file I/O, no dynamic arrays, no initial blocks.
// =============================================================================

module compute_core
  #(parameter N_RES   = 128,
    parameter N_IN    = 64,
    parameter N_OUT   = 64,
    parameter T_STEPS = 20,
    parameter DATA_W  = 32)
   (input  wire                      clk,
    input  wire                      rst_n,
    input  wire                      start,
    output reg                       done,
    input  wire [N_IN*DATA_W-1:0]    e_in,
    output reg  [N_OUT*DATA_W-1:0]   fb_out,
    output reg                       sample_pulse,
    output reg  [N_IN*DATA_W-1:0]    dac_in,
    input  wire [N_RES*DATA_W-1:0]   adc_out);

  // --------------------------------------------------------------------------
  // NODE_IDX readout map — seed=42, N=128, T=20, N_OUT=64
  // Generated by scripts/gen_reference.py
  // Packed: 64 x 7-bit fields, slot j at bits [(N_OUT-1-j)*7 +: 7]
  // Values: 88 110 24 55 111 111 76 64 51 3 57 62 100 40 27 93
  //         73 124 73 56 115  59 98 93 87 104  7 39  70 35 68 46
  //         15 104 127 80 96 71 94 49 42 77 94 104 69 114 69 17
  //         43  65  31 54 104 59 100 64 61 76 122 105 64 105 32 43
  // --------------------------------------------------------------------------
  localparam [N_OUT*7-1:0] NODE_IDX_PACK =
    {7'd43, 7'd32, 7'd105, 7'd64, 7'd105, 7'd122, 7'd76,  7'd61,
     7'd64, 7'd100,7'd59,  7'd104,7'd54,  7'd31,  7'd65,  7'd43,
     7'd17, 7'd69, 7'd114, 7'd69, 7'd104, 7'd94,  7'd77,  7'd42,
     7'd49, 7'd94, 7'd71,  7'd96, 7'd80,  7'd127, 7'd104, 7'd15,
     7'd46, 7'd68, 7'd35,  7'd70, 7'd39,  7'd7,   7'd104, 7'd87,
     7'd93, 7'd98, 7'd59,  7'd115,7'd56,  7'd73,  7'd124, 7'd73,
     7'd93, 7'd27, 7'd40,  7'd100,7'd62,  7'd57,  7'd3,   7'd51,
     7'd64, 7'd76, 7'd111, 7'd111,7'd55,  7'd24,  7'd110, 7'd88};

  // --------------------------------------------------------------------------
  // FSM states
  // --------------------------------------------------------------------------
  localparam [2:0] IDLE    = 3'd0,
                   LOAD    = 3'd1,
                   SAMPLE  = 3'd2,
                   READOUT = 3'd3,
                   DONE_ST = 3'd4;

  reg [2:0]                state_q, state_d;
  reg [4:0]                step_cnt_q, step_cnt_d;  // 5 bits covers T=20
  reg [N_RES*DATA_W-1:0]   adc_cap_q;

  // --------------------------------------------------------------------------
  // Readout gather — combinational
  // --------------------------------------------------------------------------
  reg [N_OUT*DATA_W-1:0] fb_next;
  integer gi;
  always @(*) begin
    fb_next = {(N_OUT*DATA_W){1'b0}};
    for (gi = 0; gi < N_OUT; gi = gi + 1) begin
      // slot gi is at bit position (N_OUT-1-gi)*7 in NODE_IDX_PACK
      fb_next[gi*DATA_W +: DATA_W] =
        adc_cap_q[NODE_IDX_PACK[(gi)*7 +: 7]*DATA_W +: DATA_W];
    end
  end

  // --------------------------------------------------------------------------
  // Sequential
  // --------------------------------------------------------------------------
  always @(posedge clk) begin
    if (!rst_n) begin
      state_q      <= IDLE;
      step_cnt_q   <= 5'd0;
      dac_in       <= {(N_IN*DATA_W){1'b0}};
      adc_cap_q    <= {(N_RES*DATA_W){1'b0}};
      fb_out       <= {(N_OUT*DATA_W){1'b0}};
      done         <= 1'b0;
      sample_pulse <= 1'b0;
    end else begin
      state_q      <= state_d;
      step_cnt_q   <= step_cnt_d;
      done         <= (state_d == DONE_ST);
      sample_pulse <= (state_d == LOAD) || (state_d == SAMPLE);

      if (state_q == IDLE && start)
        dac_in <= e_in;

      if (state_q == LOAD || state_q == SAMPLE)
        adc_cap_q <= adc_out;

      if (state_q == READOUT)
        fb_out <= fb_next;
    end
  end

  // --------------------------------------------------------------------------
  // FSM next-state
  // --------------------------------------------------------------------------
  always @(*) begin
    state_d    = state_q;
    step_cnt_d = step_cnt_q;
    case (state_q)
      IDLE:    if (start) begin
                 state_d    = LOAD;
                 step_cnt_d = 5'd0;
               end
      LOAD:    begin
                 step_cnt_d = step_cnt_q + 5'd1;
                 state_d    = SAMPLE;
               end
      SAMPLE:  if (step_cnt_q == 5'(T_STEPS - 1)) begin
                 state_d    = READOUT;
                 step_cnt_d = 5'd0;
               end else
                 step_cnt_d = step_cnt_q + 5'd1;
      READOUT: state_d = DONE_ST;
      DONE_ST: if (!start) state_d = IDLE;
      default: state_d = IDLE;
    endcase
  end

endmodule


// =============================================================================
// analog_crossbar_stub
// =============================================================================
module analog_crossbar_stub
  #(parameter N_IN   = 64,
    parameter N_RES  = 128,
    parameter DATA_W = 32)
   (input  wire                    clk,
    input  wire                    rst_n,
    input  wire                    sample,
    input  wire [N_IN*DATA_W-1:0]  v_in,
    output wire [N_RES*DATA_W-1:0] v_out);
  assign v_out = {(N_RES*DATA_W){1'b0}};
endmodule
