#!/usr/bin/env bash
# =============================================================================
# run_openlane_local.sh -- RC-DFA M3 local completion script
# ECE 510 Spring 2026
# Usage: cd <repo_root> && ./project/m3/run_openlane_local.sh
# =============================================================================
source /mnt/c/Users/mohal/Downloads/openlane_env/bin/activate

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
M3="$SCRIPT_DIR"

GRN='\033[0;32m'; YLW='\033[0;33m'; RST='\033[0m'
info() { echo -e "${GRN}[local]${RST} $*"; }
warn() { echo -e "${YLW}[warn]${RST} $*"; }

# ── Step 1: GTKWave waveform PNG ──────────────────────────────────────────────
info "=== Step 1: GTKWave waveform ==="
if command -v gtkwave &>/dev/null; then
    cd "$M3"
    gtkwave -S /dev/null sim/cosim_waveform.vcd -O sim/cosim_waveform.png -x \
        && info "cosim_waveform.png written" \
        || warn "GTKWave export failed -- open sim/cosim_waveform.vcd manually"
else
    warn "GTKWave not found: sudo apt install gtkwave"
fi

# ── Step 2: ngspice analog RC characterisation (full 128x128) ────────────────
info "=== Step 2: ngspice analog RC characterisation (128x128) ==="
if command -v ngspice &>/dev/null; then
    cd "$M3/analog"
    ngspice -b crossbar_rc.sp -o crossbar_rc.log 2>&1
    if grep -q "SPICE_DONE" crossbar_rc.log 2>/dev/null; then
        info "ngspice complete"
    else
        warn "ngspice may not have completed -- check analog/crossbar_rc.log"
    fi
    cd "$M3"
    python3 scripts/extract_rc_timing.py \
        && info "analog_arrival.tcl and analog_summary.txt written" \
        || warn "extract_rc_timing.py failed"
else
    warn "ngspice not found: sudo apt install ngspice"
fi

# ── Step 3: Build full SDC for OpenROAD (clock + analog arrival) ─────────────
info "=== Step 3: Building PnR SDC ==="
cat > "$M3/synth/pnr_constraints.sdc" << 'SDC'
# pnr_constraints.sdc -- clock and IO constraints for OpenROAD PnR
# Generated by run_openlane_local.sh
create_clock -name clk -period 10.0 [get_ports clk]
set_input_delay  0.5 -clock clk [get_ports {rst_n s_axis_tdata s_axis_tvalid s_axis_tlast s_axis_tkeep m_axis_tready}]
set_output_delay 0.5 -clock clk [get_ports {s_axis_tready m_axis_tdata m_axis_tvalid m_axis_tlast m_axis_tkeep sample_pulse}]
SDC

# Append analog arrival constraint (set_input_delay for adc_out from ngspice)
if [ -f "$M3/synth/analog_arrival.tcl" ]; then
    grep "^set_input_delay" "$M3/synth/analog_arrival.tcl" >> "$M3/synth/pnr_constraints.sdc"
    info "Analog arrival constraint appended to pnr_constraints.sdc"
else
    # Fallback if ngspice didn't run
    echo "set_input_delay 0.2569 -clock clk [get_ports {adc_out}]" >> "$M3/synth/pnr_constraints.sdc"
    warn "analog_arrival.tcl not found -- using fallback 0.2569ns for adc_out"
fi

# ── Step 4: OpenSTA sign-off ──────────────────────────────────────────────────
info "=== Step 4: OpenSTA ==="
if command -v sta &>/dev/null; then
    cd "$M3/synth"
    cat > sta_run.tcl << 'STATCL'
read_liberty sky130_fd_sc_hd__tt_025C_1v80.lib
read_verilog synth_netlist.v
link_design top

create_clock -name clk -period 10.0 [get_ports clk]

# Load analog arrival constraint from ngspice characterisation
if {[file exists "analog_arrival.tcl"]} {
    source analog_arrival.tcl
    puts "Analog arrival constraint loaded from analog_arrival.tcl"
} else {
    puts "WARNING: analog_arrival.tcl not found, using fallback 0.2569ns"
    set_input_delay 0.2569 -clock clk [get_ports {adc_out}]
}

set_input_delay  0.5 -clock clk [get_ports {rst_n s_axis_tdata s_axis_tvalid s_axis_tlast s_axis_tkeep m_axis_tready}]
set_output_delay 0.5 -clock clk [get_ports {s_axis_tready m_axis_tdata m_axis_tvalid m_axis_tlast m_axis_tkeep sample_pulse}]

puts "\n=== Setup timing ==="
report_checks -path_delay max -format full_clock_expanded -digits 4 > timing_sta.txt
report_checks -path_delay max -digits 4

puts "\n=== Hold timing ==="
report_checks -path_delay min -digits 4 >> timing_sta.txt

puts "\n=== WNS / TNS ==="
report_wns
report_tns

puts "\n=== Cell usage ==="
report_cell_usage > area_sta.txt
report_cell_usage

puts "\n=== Power ==="
report_power > power_sta.txt
report_power

puts "\nSTA complete."
STATCL

    sta -exit sta_run.tcl 2>&1 | tee openlane_sta.log
    info "OpenSTA done: timing_sta.txt  area_sta.txt  power_sta.txt"
else
    warn "OpenSTA not found"
fi

# ── Step 5: OpenLane 2 PnR ────────────────────────────────────────────────────
info "=== Step 5: OpenLane 2 PnR ==="
export PDK_ROOT="${PDK_ROOT:-$HOME/.volare}"
info "PDK_ROOT = $PDK_ROOT"

PDK_HASH="bdc9412b3e468c102d01b7cf6337be06ec6e9c9a"
info "Ensuring sky130A PDK is enabled..."
volare fetch --pdk sky130 "$PDK_HASH" 2>/dev/null || true
volare enable --pdk sky130 "$PDK_HASH" 2>/dev/null || true

cd "$M3/synth"

cat > config.json << 'OLCFG'
{
    "DESIGN_NAME": "top",
    "VERILOG_FILES": [
        "dir::../rtl/top.sv",
        "dir::../rtl/interface_mod.sv",
        "dir::../rtl/compute_core.sv"
    ],
    "CLOCK_PORT": "clk",
    "CLOCK_PERIOD": 10.0,
    "PDK": "sky130A",
    "STD_CELL_LIBRARY": "sky130_fd_sc_hd",
    "SYNTH_STRATEGY": "AREA 0",
    "MAX_FANOUT_CONSTRAINT": 16,
    "FP_CORE_UTIL": 30,
    "PL_TARGET_DENSITY_PCT": 25,
    "DIE_AREA": "0 0 4500 4500",
    "FP_SIZING": "absolute",
    "RUN_POST_GRT_RESIZER_TIMING": true,
    "RUN_CTS": true,
    "RUN_FILL_INSERTION": true,
    "PNR_SDC_FILE": "dir::pnr_constraints.sdc",
    "SIGNOFF_SDC_FILE": "dir::pnr_constraints.sdc"
}
OLCFG

VENV=/mnt/c/Users/mohal/Downloads/openlane_env
export PATH="$VENV/bin:$PATH"

sudo nix --extra-experimental-features 'nix-command flakes' \
    run github:efabless/openlane2 -- --pdk-root "$PDK_ROOT" config.json \
    2>&1 | tee openlane_pnr.log

RUN_DIR=$(ls -td runs/RUN_* 2>/dev/null | head -1)
if [ -n "$RUN_DIR" ]; then
    info "OpenLane run: $RUN_DIR"
    find "$RUN_DIR" -name "*.rpt" -o -name "*.txt" 2>/dev/null \
        | grep -iE "timing|area|power|sta" \
        | while read f; do
            cp "$f" "$M3/synth/openlane_$(basename $f)" 2>/dev/null || true
          done
    info "Reports copied to synth/"
else
    warn "No OpenLane run directory found -- check openlane_pnr.log"
fi

info "=== All steps complete ==="
echo ""
echo "Files produced:"
echo "  analog/crossbar_rc.log     (ngspice: timing, power, routing -- 128x128)"
echo "  analog/analog_summary.txt  (human-readable analog results)"
echo "  synth/analog_arrival.tcl   (set_input_delay from ngspice t99)"
echo "  synth/pnr_constraints.sdc  (full SDC for OpenROAD: clock + analog)"
echo "  sim/cosim_waveform.png     (GTKWave annotated waveform)"
echo "  synth/timing_sta.txt       (OpenSTA setup/hold)"
echo "  synth/area_sta.txt         (OpenSTA cell usage)"
echo "  synth/power_sta.txt        (OpenSTA power)"
echo "  synth/openlane_pnr.log     (OpenLane 2 PnR full log)"
echo "  synth/openlane_*.rpt       (OpenLane timing/area/power reports)"