#!/usr/bin/env python3
"""
extract_rc_timing.py  --  Parse ngspice log -> analog_arrival.tcl + summary
ECE 510 Spring 2026  --  M3
"""
import re, os, math

log_path     = os.path.join(os.path.dirname(__file__), '..', 'analog', 'crossbar_rc.log')
tcl_path     = os.path.join(os.path.dirname(__file__), '..', 'synth',  'analog_arrival.tcl')
summary_path = os.path.join(os.path.dirname(__file__), '..', 'analog', 'analog_summary.txt')

if not os.path.exists(log_path):
    print(f"ERROR: {log_path} not found"); raise SystemExit(1)

with open(log_path) as f:
    log = f.read()

def parse_val(text, key):
    m = re.search(rf'\b{re.escape(key)}\s*=\s*([\d.e+\-]+)', text, re.IGNORECASE)
    return float(m.group(1)) if m else None

# Timing
t_10 = parse_val(log, 't_10')
t_90 = parse_val(log, 't_90')
t_99 = parse_val(log, 't_99')

if t_10 is None or t_90 is None:
    print(f"ERROR: Could not parse t_10/t_90 from {log_path}")
    print("First 30 lines of log:")
    for line in log.splitlines()[:30]:
        print(" ", line)
    raise SystemExit(1)

tau        = (t_90 - t_10) / math.log(9)
tau_ns     = tau * 1e9
t99_ns     = t_99 * 1e9 if t_99 else tau_ns * 4.6
bw_GHz     = 1.0 / (2 * math.pi * tau) / 1e9
margin_ns  = 1.0 - tau_ns

# Routing geometry (128x128, 128 um pitch)
row_wire_um   = 128.0 * 128.0   # total row wire per row = 128 cells * pitch
col_wire_um   = 128.0 * 128.0
# Use values printed by ngspice if available, else computed
row_R_ohm     = parse_val(log, 'row_r') or 0.1 * row_wire_um
col_R_ohm     = parse_val(log, 'col_r') or 0.1 * col_wire_um
row_C_fF      = parse_val(log, 'row_c_ff') or 0.2 * row_wire_um
col_C_fF      = parse_val(log, 'col_c_ff') or 0.2 * col_wire_um
total_wire_mm = parse_val(log, 'Total interconnect') or \
                (128 * row_wire_um + 128 * col_wire_um) / 1e6
area_mm2      = 0.016384   # 128x128 um^2 assumed array footprint

# Power -- try old-style named vars first, then compute from v_drive_avg
P_avg_uW    = parse_val(log, 'P_avg_array_uW')
P_peak_mW   = parse_val(log, 'P_peak_array_mW')
P_static_uW = parse_val(log, 'P_static_array_uW')
P_density   = parse_val(log, 'P_density_mW_mm2')

if P_avg_uW is None:
    # RC crossbar: no resistive load -- power is CV²f (charging energy)
    # Total column capacitance = 128 rows * col_C_fF per col
    C_total_fF = 128 * col_C_fF          # fF
    C_total_F  = C_total_fF * 1e-15
    V_drive    = 1.8                      # V (sky130 VDD)
    f_op       = 100e6                    # Hz (100 MHz clock)
    P_avg_W    = 0.5 * C_total_F * V_drive**2 * f_op
    P_avg_uW   = P_avg_W * 1e6

    v_drive_peak = parse_val(log, 'v_drive_peak')
    if v_drive_peak is not None:
        P_peak_mW = 0.5 * C_total_F * v_drive_peak**2 * f_op * 1e3

print("=" * 60)
print("ANALOG RESULTS  --  128x128 Full Array (direct measurement)")
print("RC-DFA Memcapacitive Crossbar  --  ECE 510 Spring 2026")
print("=" * 60)
print(f"\nTIMING")
print(f"  t_10         = {t_10*1e12:.3f} ps")
print(f"  t_90         = {t_90*1e12:.3f} ps")
print(f"  t_99         = {t99_ns*1e3:.3f} ps" if t_99 else "  t_99        = not parsed")
print(f"  tau_RC       = {tau*1e12:.3f} ps  ({tau_ns:.6f} ns)")
print(f"  Bandwidth    = {bw_GHz:.3f} GHz")
print(f"  Margin @1GHz = {margin_ns:.4f} ns  ({'PASS' if margin_ns > 0 else 'FAIL'})")

print(f"\nPOWER (128x128 full array)")
if P_avg_uW:
    print(f"  Average      = {P_avg_uW:.4f} uW  ({P_avg_uW/1000:.6f} mW)")
    print(f"  Peak         = {P_peak_mW:.4f} mW" if P_peak_mW else "  Peak        = not parsed")
    print(f"  Static lkg   = {P_static_uW:.4f} uW" if P_static_uW else "  Static      = not parsed")
else:
    print("  (not parsed from log -- check v_drive_avg/v_col_avg in crossbar_rc.log)")

print(f"\nPOWER DENSITY")
print(f"  Array area   = {area_mm2*1e6:.0f} um^2  ({area_mm2:.6f} mm^2)")
if P_density:
    print(f"  Density(avg) = {P_density:.4f} mW/mm^2")
elif P_avg_uW:
    computed = P_avg_uW / (area_mm2 * 1000)
    print(f"  Density(avg) = {computed:.4f} mW/mm^2  (computed)")

print(f"\nROUTING")
print(f"  Row wire/row = {row_wire_um:.0f} um  R={row_R_ohm:.2f} Ohm  C={row_C_fF:.2f} fF")
print(f"  Col wire/col = {col_wire_um:.0f} um  R={col_R_ohm:.2f} Ohm  C={col_C_fF:.2f} fF")
print(f"  Total wires  = {total_wire_mm:.3f} mm")
print("=" * 60)

# Write analog_arrival.tcl
os.makedirs(os.path.dirname(tcl_path), exist_ok=True)
with open(tcl_path, 'w') as f:
    f.write(f"# analog_arrival.tcl -- auto-generated by extract_rc_timing.py\n")
    f.write(f"# Source: ngspice crossbar_rc.sp -- 128x128 direct measurement\n#\n")
    f.write(f"# TIMING\n")
    f.write(f"#   t_10     = {t_10*1e12:.3f} ps\n")
    f.write(f"#   t_90     = {t_90*1e12:.3f} ps\n")
    f.write(f"#   tau      = {tau*1e12:.3f} ps  ({tau_ns:.6f} ns)\n")
    if t_99: f.write(f"#   t_99     = {t99_ns*1e3:.3f} ps  ({t99_ns:.6f} ns)\n")
    f.write(f"#   BW       = {bw_GHz:.3f} GHz\n")
    f.write(f"#   Margin   = {margin_ns:.4f} ns @ 1 GHz  ({'PASS' if margin_ns > 0 else 'FAIL'})\n")
    if P_avg_uW:
        f.write(f"#\n# POWER (128x128 full array)\n")
        f.write(f"#   Average  = {P_avg_uW:.4f} uW\n")
        if P_peak_mW:  f.write(f"#   Peak     = {P_peak_mW:.4f} mW\n")
        if P_density:  f.write(f"#   Density  = {P_density:.4f} mW/mm^2\n")
    f.write(f"#\n# ROUTING\n#   Total    = {total_wire_mm:.3f} mm\n#\n")
    f.write(f"# Input delay = t99 settling time\n")
    f.write(f"set_input_delay {t99_ns:.6f} -clock clk [get_ports {{adc_out}}]\n")

print(f"\nWrote: {tcl_path}")

# Write summary
os.makedirs(os.path.dirname(summary_path), exist_ok=True)
with open(summary_path, 'w') as f:
    f.write("Analog Characterisation Summary -- 128x128 Full Array\n")
    f.write("RC-DFA Memcapacitive Crossbar  --  ECE 510 Spring 2026\n")
    f.write("=" * 60 + "\n\n")
    f.write(f"TIMING\n")
    f.write(f"  t_10         = {t_10*1e12:.3f} ps\n")
    f.write(f"  t_90         = {t_90*1e12:.3f} ps\n")
    if t_99: f.write(f"  t_99         = {t99_ns*1e3:.3f} ps\n")
    f.write(f"  tau_RC       = {tau*1e12:.3f} ps  ({tau_ns:.6f} ns)\n")
    f.write(f"  Bandwidth    = {bw_GHz:.3f} GHz\n")
    f.write(f"  Margin @1GHz = {margin_ns:.4f} ns  ({'PASS' if margin_ns > 0 else 'FAIL'})\n\n")
    if P_avg_uW:
        f.write(f"POWER (128x128 array)\n")
        f.write(f"  Average      = {P_avg_uW:.4f} uW\n")
        if P_peak_mW:  f.write(f"  Peak         = {P_peak_mW:.4f} mW\n")
        if P_static_uW: f.write(f"  Static lkg   = {P_static_uW:.4f} uW\n")
        computed_density = P_avg_uW / (area_mm2 * 1000)
        f.write(f"\nPOWER DENSITY\n  {computed_density:.4f} mW/mm^2  (over {area_mm2*1e6:.0f} um^2)\n")
    f.write(f"\nROUTING (128x128)\n")
    f.write(f"  Total wire   = {total_wire_mm:.3f} mm\n")
    f.write(f"  Row: {row_wire_um:.0f} um/row  R={row_R_ohm:.2f} Ohm  C={row_C_fF:.2f} fF\n")
    f.write(f"  Col: {col_wire_um:.0f} um/col  R={col_R_ohm:.2f} Ohm  C={col_C_fF:.2f} fF\n")

print(f"Wrote: {summary_path}")