#!/usr/bin/env python3
"""
gen_reference_m3.py  --  Generate FP32 reference values for tb_top.sv
ECE 510 Spring 2026  --  M3
"""
import numpy as np
import struct, os

N_IN  = 64
N_RES = 128
N_OUT = 64
T     = 20
SEED  = 42

rng  = np.random.RandomState(SEED)
W_in  = rng.randn(N_RES, N_IN ).astype(np.float32) * 0.1
W_res = rng.randn(N_RES, N_RES).astype(np.float32) * 0.1

rng2 = np.random.RandomState(7)
e_in = rng2.randn(N_IN).astype(np.float32)

norm  = float(np.linalg.norm(e_in))
e_norm = (e_in / (norm + 1e-8)).astype(np.float32)

s = np.tanh(e_norm @ W_in.T).astype(np.float32)
for _ in range(T - 1):
    s = np.tanh(s @ W_res.T).astype(np.float32)

fb_ref = np.array([s[j % N_RES] for j in range(N_OUT)], dtype=np.float32)
assert np.all(np.isfinite(fb_ref))

print(f"Reference stats: min={fb_ref.min():.6f} max={fb_ref.max():.6f} "
      f"mean={fb_ref.mean():.6f} std={fb_ref.std():.6f}")

def to_hex(arr):
    return [struct.pack('>f', float(v)).hex() for v in arr]

def pack_flat(hex_words):
    return ''.join(reversed(hex_words))

e_hex  = to_hex(e_in)
fb_hex = to_hex(fb_ref)

out_dir = os.path.join(os.path.dirname(__file__), '..', 'tb')
os.makedirs(out_dir, exist_ok=True)
svh_path = os.path.join(out_dir, 'tb_reference_m3.svh')

with open(svh_path, 'w', encoding='ascii') as f:
    f.write("// Auto-generated by gen_reference_m3.py -- do not edit\n")
    f.write(f"// N_IN={N_IN} N_RES={N_RES} N_OUT={N_OUT} T={T} W_seed={SEED} e_seed=7\n")
    f.write(f"// fb_ref: min={fb_ref.min():.8f} max={fb_ref.max():.8f}\n\n")
    f.write(f"parameter logic [2047:0] REF_E_IN   = 2048'h{pack_flat(e_hex)};\n\n")
    f.write(f"parameter logic [2047:0] REF_FB_OUT = 2048'h{pack_flat(fb_hex)};\n\n")
    # Write per-word as individual localparam constants (iverilog-safe)
    for j, hx in enumerate(fb_hex):
        f.write(f"parameter logic [31:0] REF_FB_{j:03d} = 32'h{hx};\n")

print(f"Wrote {svh_path}")

# Write table
txt_path = os.path.join(os.path.dirname(__file__), 'reference_m3.txt')
with open(txt_path, 'w') as f:
    f.write("# M3 Reference Values -- RC-DFA Reservoir Model (FP32)\n")
    f.write(f"# N_IN={N_IN} N_RES={N_RES} N_OUT={N_OUT} T={T}\n\n")
    f.write(f"{'ch':>4}  {'fb_out (float)':>18}  hex\n")
    f.write("-" * 42 + "\n")
    for j, (v, hx) in enumerate(zip(fb_ref, fb_hex)):
        f.write(f"{j:4d}  {v:+18.10e}  {hx}\n")
print(f"Wrote {txt_path}")
print("Done.")
